### ISSUE TITLE
Missing obj directory

### ISSUE THREAD

**Issue by djromero** [jerem/psdparse#1]
Build doesn't work in OSX 10.6 because there is a missing "obj" directory. 
Using latest developer tools.

```
$make
...
/var/folders/U1/U1oCRpb1GCGhQGYyPqTb1U+++TI/-Tmp-//ccCW8E5e.s:unknown:FATAL:can't create output file: obj/main.o
make: *** [obj/main.o] Error 1
$mkdir obj
$make
```

**Comment by jerem** [comment]
Sorry but this fork is only about Python code. I have stripped out all of the C code, the repository was no up to date. Checkout the latest version.
